[members]
grace = "Grace Lee <grace@example.com>"
henry = "Henry Brown <henry@example.com>"

[iteration.status.map]
todo = { category = "todo", order = 10 }
backlog = { category = "todo", order = 20 }
in_progress = { category = "in_progress", order = 30 }
testing = { category = "in_progress", order = 40 }
done = { category = "done", order = 50 }
